using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ExamProjectFirstYear
{
	/// <summary>
	/// "Tag" enum with all component tags.
	/// </summary>
	public enum Tag
	{
		COLLIDER,
		SPRITERENDERER,
		GAMEOBJECT,
		PLAYER,
		MEELEEENEMY,
		FLYINGENEMY,
		RANGEDENEMY,
		NPC,
		BOSS,
		ITEM,
		PLATFORM,
		DOOR,
		GRAVITY,
		LIGHTSOURCE,
		PROJECTILE,
		BOSSPROJECTILE,
		PLAYERMELEEATTACK,
		PLAYERPROJECTILE,
		ENEMYPROJECTILE,
		MOVEMENT,
		MATERIAL,
		MATCHHEAD,
		SPIDERFILAMENT,
		MOTHWING,
		BLUEPRINT,
		JOURNAL,
		INVENTORY,
		ENEMY,
		ATTACKMELEE,
		PLAYERHEALTHUI,
		PLAYERMANAUI,
		MENUHANDLER,
		JUMP,
		ENEMYATTACKSTATE,
		ENEMYIDLESTATE,
		RANGEDATTACK,
		MELEEATTACK,
		ATTACKRANGED,
		ENEMYMELEEATTACK,
		SOUNDCOMPONENT,
		WALL
	}
}
